### ISSUE TITLE
close() - You must call the send function from a coroutine

### ISSUE THREAD

**Issue by endel** [britzl/defold-websocket#1]
Hey @britzl, first of all, thanks a lot for this client! It's being great to use it.

We're having one problem, though. When calling the `close()` method, I'm having this error:

```
ERROR:SCRIPT: /websocket/client_async.lua:65: You must call the send function from a coroutine
stack traceback:
	[C]: in function 'assert'
	/websocket/client_async.lua:65: in function 'sock_send'
	/websocket/sync.lua:100: in function 'sync_close'
	/websocket/client_async.lua:231: in function 'close'
	/colyseus/connection.lua:77: in function 'close'
```

Maybe this function should be all inside a coroutine? https://github.com/britzl/defold-websocket/blob/bad3bb481ae3b57d15833f015ecedef657938e9e/websocket/client_async.lua#L224-L233

Cheers!

**Comment by britzl** [comment]
Good catch! Released 1.0.1 to fix this: https://github.com/britzl/defold-websocket/releases/tag/1.0.1
