### ISSUE TITLE
on_connected event, error not being reported

### ISSUE THREAD

**Issue by GreenArrow18** [britzl/defold-websocket#11]
Expected results: if connection fails (e.g. server is offline), on_connected should return a connection refused/failed error, so the program can take appropriate actions

What happens:
1. On Windows, no error is being reported in both the Defold editor and html5 builds.
2. On Mac, no error is being reported in the html5 build. An error is properly returned in the Defold editor.

**Comment by britzl** [comment]
I'm able to reproduce this myself as well. getaddrinfo() returns data and I'm not getting an error from sock:connect() or socket.select().

I've added an optional and configurable timeout to the connect to a branch. Would you mind giving it a try on Windows as well? https://github.com/britzl/defold-websocket/tree/connect_timeout

**Comment by GreenArrow18** [comment]
In the html5 build, I am actually getting a websocket error from the console immediately:
![defold7](https://user-images.githubusercontent.com/45327771/48994869-50e39480-f180-11e8-85ca-dca429624970.png)

The problem is, the extension doesn't seem to be capturing this particular error. So I was wondering if we really have to resort to a time-out? Is the actual websocket error getting lost somehow?

In any case, yes I can confirm the timeout works quite well, in both the Defold editor and html5 builds. Thanks!

**Comment by britzl** [comment]
I haven't figured this out yet. From my tests I haven't found a way to catch this on the Lua side.
