### ISSUE TITLE
Problem with building example on windows

### ISSUE THREAD

**Issue by Laminariy** [britzl/defold-websocket#16]
When I try to build an example, it gives an error

/luasec/src/luasocket/timeout.c
	Line 10: 'Winsock2.h' file not found
#include <Winsock2.h>
         ^~~~~~~~~~~~

But HTML5 works fine

**Comment by britzl** [comment]
Fixed. The LuaSec dependency needed to be updated to 1.0.1 where the include name for WinSock2.h was fixed.
