### ISSUE TITLE
Emulation an Android with dmengine 1.2.155 causes "attempt to index upvalue 'mime' (a nil value)"

### ISSUE THREAD

**Issue by joernlenoch** [britzl/defold-websocket#17]
Thank you very much for this extension!

While it works fine when compiled into an APK and transferred manually to my phone, it causes a
```
/websocket/tools.lua:162: attempt to index upvalue 'mime' (a nil value)
```
error when used with the Defold Android Engine. 

I'm currently using it in conjunction with the defold engine apk (Version 1.2.155) on my Android Phone (Version 9; OxygenOS 9.0.5).

I have to assume that I must be caused by this extension.

Thank you very much for any help!

```
dependencies = 
https://github.com/britzl/defold-websocket/archive/master.zip,
https://www.github.com/britzl/defold-luasocket/archive/master.zip,
https://github.com/britzl/defold-luasec/archive/master.zip,
https://github.com/andsve/dirtylarry/archive/master.zip,
https://github.com/Melsoft-Games/defold-cjson/archive/master.zip,
https://github.com/britzl/ludobits/archive/master.zip,
https://github.com/britzl/defold-orthographic/archive/2.8.0.zip,
https://github.com/britzl/defpro/archive/master.zip,
https://github.com/subsoap/defblend/archive/master.zip,
https://github.com/britzl/defold-input/archive/master.zip
```

**Comment by britzl** [comment]
When you download a dmengine.apk from d.defold.com you get a completely clean/vanilla version of the engine without any native extensions included. This works well for cases where the project you are working on contains no native extensions, however in your case the mime namespace (part of defold-luasocket) is a native extension and that is not included in the vanilla version of the engine.

The solution is to simply bundle a debug version of your application and install that on your phone. This debug version will obviously include the native extension code (mime in this case) and you will be able to target this application instead for hot-reload etc.

**Comment by joernlenoch** [comment]
Thank you very much!!

I guess it will simultaneously fix my issues with wrong orientation... Thank you!

**Comment by britzl** [comment]
Yes it will solve orientation issues as well!
