### ISSUE TITLE
Support PING / PONG messages

### ISSUE THREAD

**Issue by endel** [britzl/defold-websocket#2]
Hey @britzl,

I'm trying to allow your library to respond to PING messages. It seems some PING messages aren't received sometimes.

So far, I've found that when the PING comes, it can be received here, and sometimes it doesn't: https://github.com/britzl/defold-websocket/blob/b480623cb2efe0e920b4d3d30ef61aeb209549ab/websocket/sync.lua#L25

I've added a check for `opcode == 0x9` [here](https://github.com/britzl/defold-websocket/blob/b480623cb2efe0e920b4d3d30ef61aeb209549ab/websocket/client_async.lua#L163-L164) to automatically send the `PONG` messages:

```lua
if opcode == 0x9 then
    -- reply PING opcode with PONG
    print("REPLY WITH PONG")
    self.send(self, message, 0xA)
elseif message then
    on_message(message)
end
```

My server logs are looking like this ([Colyseus](https://github.com/gamestdio/colyseus) automatically disconnects users after 3 PING's without response 😢 )

```
SEND PING
SEND PING
PONG RECEIVED!
SEND PING
SEND PING
SEND PING
```

Do you have any clue why? Cheers!

**Comment by endel** [comment]
FYI this problem doesn't happen in `emscripten` environment since the browser handles PING/PONG messages automatically

**Comment by britzl** [comment]
In the official LuaWebsocket project there's an issue discussing PING/PONG: https://github.com/lipp/lua-websockets/issues/94
