### ISSUE TITLE
HTTPS on HTML5 environment

### ISSUE THREAD

**Issue by endel** [britzl/defold-websocket#8]
Hi @britzl,

I've noticed that this library doesn't play nicely on HTTPS environment. 

When loading the page from an `https://` URL, the client tries to connect to `ws://raftwars.io:443`, which results in `Mixed Content` error:

```
Mixed Content: The page at 'https://...' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://...:443/?colyseusid='. This request has been blocked; this endpoint must be available over WSS.
```

I'm currently checking if it's feasible to change the WebSocket constructor on the final .js built file as a workaround. Would be great to have this as part of the build process, though.

Do you have any idea why this happens? AFAIK it's not at all related to `luasec`, since the browser should handle `wss://` automatically.

Cheers!

**Comment by endel** [comment]
I've debugged a bit further the JS output, and this is the function that is causing the problem (`SOCKFS.websocket_sock_ops.createPeer`) - which seems to come from emscripten

![screen shot 2018-08-07 at 10 49 55](https://user-images.githubusercontent.com/130494/43779836-acdbd5b6-9a2f-11e8-978c-5882be61b508.png)

I'm not sure where the `{{{ WEBSOCKET_URL }}}` is coming from in emscripten, but it should be `wss://` instead of `ws://` on this point: https://github.com/kripken/emscripten/blob/cd42e9d1da3afae66ddbc57ec009fb00c26c7eb9/src/library_sockfs.js#L163-L168

**Comment by endel** [comment]
Created a pull-request for them here, not sure if it's going to be taken seriously, or if I'm missing something: https://github.com/kripken/emscripten/pull/6960

**Comment by britzl** [comment]
Thanks! Yeah, this seems to require an emscripten update, and then Defold needs to upgrade as well. Let's see how it goes with that pull request first.

**Comment by endel** [comment]
Hi @britzl, thanks for checking out.

I think what they're saying makes perfect sense actually. We could add the code I've created as a pull-request on the generated `dmengine.js` if that's possible.

**Like this:**

```
/* ********************************************************************* */
/* Module is Emscripten namespace                                        */
/* ********************************************************************* */

var Module = {
    // ...
    websocket: { url: window.location.protocol.replace("http", "ws") + "//" },
    // ...
}
```

**Comment by britzl** [comment]
Yes, or perhaps using html5.run()? I'm going to create a branch where we can test this.

**Comment by britzl** [comment]
Would you mind testing this branch: https://github.com/britzl/defold-websocket/tree/html5_mixedcontent

**Comment by endel** [comment]
Thanks a lot @britzl, it works. I've just noticed that some errors are being triggered, though:

```
INFO:CRASH: Successfully wrote Crashdump to file: /data/.Defold/_crash
MyProject.js:1 Uncaught TypeError: Module.websocket.emit is not a function
    at handleMessage (MyProject.js:1)
    at WebSocket.peer_socket_onmessage (MyProject.js:1)
```

It's funny because the communication works even though these errors are popping multiple times.

**Comment by britzl** [comment]
Ah, I redefine Module.websocket at runtime, after it's been set up. This does ofcourse remove anything set to the Module.websocket object:

https://github.com/kripken/emscripten/blob/master/src/library_sockfs.js#L6-L9

My code should probably append to the object if it exists. Gonna see if I can get that to work.

**Comment by britzl** [comment]
I've pushed a new commit to the branch. Would you mind trying? Or do you have a way for me to test?

**Comment by endel** [comment]
Thanks a lot, @britzl! It works without any errors in the console now! <3

**Comment by britzl** [comment]
Merged to master and released.

https://github.com/britzl/defold-websocket/releases/tag/1.3.3
